# docker-compose.yml

version: '3'
services:
  django:
    build: ./apiwork
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.ru
      - DJANGO_SUPERUSER_PASSWORD=admin
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=movies_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_PORT=5423
      - POSTGRES_HOST=127.0.0.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - django
    ports:
      - "80:80"
volumes:
  postgres_data: